Revert "Add prerequisites for root for alpine docker image"
This reverts commit 45a44f3afe7b1dea2b3c1472350eb5666a8456d7.

Abandon attempt to build ROOT inside the alpine docker docker container
due to TBB not building with:

../../build/Makefile.tbb:32: CONFIG: cfg=release arch=intel64 compiler=gcc target=linux runtime=cc6.2.1_libc_kernel4.3.0 getconf: GNU_LIBC_VERSION: unknown variable
../../src/tbbmalloc/proxy.cpp: In function 'mallinfo mallinfo()':
../../src/tbbmalloc/proxy.cpp:188:26: error: return type 'struct mallinfo' is incomplete  struct mallinfo mallinfo() __THROW